### ISSUE TITLE
RFC: Create a `PacketDelta` object

### ISSUE THREAD

**Issue by sdwilsh** [sdwilsh/siobrultech-protocols#44]
I'm wondering if it makes sense to add a method on `Packet` that, given another `Packet`, computes a `PacketDelta` which does pretty much everything (in terms of math) that [this code](https://github.com/jkeljo/greeneye-monitor/blob/master/greeneye/monitor.py#L117) does.

It's also possible that the right thing to do here is to create a `get_average_power(self, packet: Packet) -> float` method to compute the average watts based on [this code](https://github.com/jkeljo/greeneye-monitor/blob/master/greeneye/monitor.py#L135).

@jkeljo, any thoughts?

**Comment by jkeljo** [comment]
Yeah, I think pushing some of that logic down here makes sense. I think starting with `get_average_power` (and `get_average_pulse_rate`, which would do the same thing for pulse counters) would be a good first step. That would let me remove ~40 lines of code. What would remain is just change detection to decide whether to issue a notification, which isn't particularly unique to this space.

**Comment by sdwilsh** [comment]
Closed with #66.
