### ISSUE TITLE
Closing transports?

### ISSUE THREAD

**Issue by jkeljo** [sdwilsh/siobrultech-protocols#48]
I've been working on adding configuration support to `greeneye-monitor`. One of my test programs does the following:

1. Connects to the GEM and instructs it to send packets to the machine running the test program
2. Creates a server to listen for packets
3. Upon interrupt, close that server
4. Connect to the GEM again and instruct it to send packets to my Home Assistant instance

As currently written, each of those "connects to the GEM" steps involves doing a [`loop.create_connection`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection) with a new instance of the protocol and sending a serial number request to it.

This is all horribly inefficient, but it did expose an issue that I think needs dealing with.

Here's what the logs look like for steps 3 and 4:

```
^C2021-12-31 15:19:57,721 [greeneye.monitor](INFO) Closing server on ('0.0.0.0', 8000)
2021-12-31 15:19:57,724 [greeneye.monitor](DEBUG) queue consumer is getting canceled
2021-12-31 15:19:57,737 [siobrultech_protocols.gem.protocol](INFO) Connection opened
2021-12-31 15:19:57,738 [siobrultech_protocols.gem.protocol](DEBUG) Starting API request. Requesting packet delay...
2021-12-31 15:20:00,743 [siobrultech_protocols.gem.protocol](DEBUG) Sending API request '^^^RQSSRN'...
2021-12-31 15:20:00,771 [siobrultech_protocols.gem.protocol](DEBUG) Received 10 bytes
2021-12-31 15:20:00,772 [siobrultech_protocols.gem.protocol](DEBUG) Received 10 bytes
2021-12-31 15:20:00,772 [siobrultech_protocols.gem.protocol](DEBUG) No header found. Discarding junk data: bytearray(b'XXXXXXXX\r\n')
2021-12-31 15:20:03,747 [siobrultech_protocols.gem.protocol](DEBUG) Received API response: 'XXXXXXXX
'
2021-12-31 15:20:03,747 [siobrultech_protocols.gem.protocol](DEBUG) Ended API request
```

Even though the server was closed, the established connection remains. Because of the way the network connection works on the GEM, the response for any request is sent to both connections. As a result, we get one protocol instance complaining about a malformed packet while the other one is handling an expected API response. The only impact of this for the test program was some janky debug logging, but in Home Assistant I could imagine it throwing exceptions all over the place after attempting to unload the component because it's trying to update entities that should be dead.

Now, all of this is expected per [the docs for `Server.close`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.Server.close)... when you close the server, existing connections remain open. The way you close existing connections is by closing the corresponding `Transport`s.

Which at last brings me to the reason I filed this issue. What's the cleanest way for us to find and close those transports? I've subclassed `BidirectionalProtocol` already, so I could do this in my library, but I'm wondering if this is something that should somehow be handled here.

Thoughts?

**Comment by sdwilsh** [comment]
Hmm, this is certainly something I do not need to handle with serial transports (at least, in practice, since they never go away).

> Because of the way the network connection works on the GEM, the response for any request is sent to both connections.

This is kinda crazy, but I understand why it does that.

> What's the cleanest way for us to find and close those transports?

I'm not sure I have a good answer here, to be honest.  Any solution we'd do here would be transport and connection-specific, right?

**Comment by jkeljo** [comment]
Given that the server is outside the scope of this library, we certainly can't do anything automatic. If we do nothing here, what I'll probably end up doing is having my protocol subclass track its transport and work with the server to keep a list of protocol instances that have valid transports so that the server can close them all. The potentially generalizable parts of that might look like having `PacketProtocol` expose its transport (or a `close` method) and send messages to the queue when it gets or loses its connection (so that an external entity can track active protocol instances).

**Comment by sdwilsh** [comment]
Would it be a 1:1 mapping of `PacketProtocol` to a transport, or is it re-used?

**Comment by jkeljo** [comment]
The asyncio docs are not explicit about that, but there are a few places
where they imply that a protocol is created per transport.

**Comment by sdwilsh** [comment]
I think it's reasonable then for us to expose something here.

**Comment by jkeljo** [comment]
Ok, I'll work on it.
